GET http://localhost:8080/accounts

###

POST localhost:8080/accounts
Content-Type: application/json

{
  "login": "newlog",
  "email": "newusermail.com",
  "firstName": "jnkjn",
  "lastName": "userov",
  "age": 18
}

###

PUT http://localhost:8080/accounts/3
Content-Type: application/json

{
  "login": "somenewlogin",
  "email": "alice@mail.com",
  "firstName": "Alice",
  "lastName": "Alice",
  "age": 19
}

###

DELETE http://localhost:8080/accounts/4

###

GET http://localhost:8080/chatRooms

###

POST http://localhost:8080/chatRooms
Content-Type: application/json

{
  "name": "some room"
}

###

POST http://localhost:8080/chatRooms/1/addAccount/49

###

POST localhost:8080/chatRooms/1/deleteAccount/4

###

GET http://localhost:8080/chatRooms/1/messages

###

POST http://localhost:8080/chatRooms/17/messages
Content-Type: application/json

{
  "body": "some new message text",
  "accountId": 4
}

###

GET http://localhost:8080/accounts/477/messages

###

DELETE http://localhost:8080/chatRooms/1/messages?messageId=1
